CREATE TABLE PERSON (ID BIGINT  PRIMARY KEY AUTO_INCREMENT,FIRST_NAME VARCHAR(255),LAST_NAME VARCHAR(255),ADDRESS VARCHAR(255));
insert into PERSON(FIRST_NAME, LAST_NAME, ADDRESS) values ('John','Peter','Chennai');
insert into PERSON(FIRST_NAME, LAST_NAME, ADDRESS) values ('Alice','Bob','Chennai');
insert into PERSON(FIRST_NAME, LAST_NAME, ADDRESS) values ('William','John','Chennai');